# -*- coding: utf-8 -*-


# =============================================================================
# Project Configuration
# =============================================================================

[tool.poetry]
name = "swing_hello"
version = "0.2.2"
description = "A Django plugin that provides basic views for response handling and template rendering."
authors = ["Scape Agency <info@scapeagency.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://www.swing.dj"
repository = "https://github.com/scape-agency/swing-hello"
documentation = "https://hello.swing.dj"
keywords = ["Django", "plugin", "views", "template", "response-handling"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Django",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "src/**",
    "README.md",
    "LICENSE",
    "docs/**",   # Include documentation in the package
]
packages = [{ include = "swing", from = "src" }]

# =============================================================================
# Dependencies
# =============================================================================

[tool.poetry.dependencies]
python = ">=3.12, <3.13"
django = "5.2.7"


# =============================================================================
# Development Dependencies
# =============================================================================

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"        # Framework for testing
pytest-django = "^4.5.2"
pytest-cov = "^6.1.1"    # Code coverage for tests
black = "^25.1.0"        # Code formatter
flake8 = "^7.2.0"        # Linter for code quality
mypy = "^1.15.0"         # Static type checker
sphinx = "^8.0.2"        # Documentation generator
isort = "^6.0.0"         # Import sorter
tox = "^4.25.0"          # Testing multiple environments
pre-commit = "^4.1.0"    # Pre-commit hooks for linting and formatting


# =============================================================================
# Build System
# =============================================================================

[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"


# =============================================================================
# Scripts
# =============================================================================

[tool.poetry.scripts]
swing_hello = "swing.hello.__main__:main" # Entry point for the package


# =============================================================================
# Plugins
# =============================================================================

[tool.poetry.plugins."django.apps"]
"swing_hello" = "swing.hello.apps.SwingHelloConfig"
